language: node_js
node_js:
- 10.16.3
before_script:
  export NODE_OPTIONS=--max_old_space_size=4096
cache:
  directories:
    - node_modules
    - $HOME/.npm
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - secure: "BzW6W+iNcAn3c0uCQC3RDA4KnZFMikrCOLaqYtt1Wr8D3AhpgicFX/V2mW8YJRPbiDji7bDwK0d19Spi51Y4db2InSvMWe0CgYdPzSMhaQJ4YlNFfOlZcXGfTIo9CHgutHSqvOiyNOdLeLJ2PNZutn+d+TWoMqsF6TZLUK4F9G6Uo8AfYUXyjUbuI2WN4rVGEMP3VCHLs6qn3sbJLSoGA5oLY7zD4+bcFqmQoL5PROoL5dCQ3pOX7QXCY214eaye4m4WesoIZsrIOQTZNLpg9a7zSDvrT/3dK3GQrRoxv555M2QPx+/gJ514+Z7VmJ5ht9+lZl4DjFRw2OY0AeGaBqmRYj6JEdczkDwYBa6UXb/Ar/ESOpcNshx9GYWX+JA0b6Uxgqcw9cjcZXTkBK5urfexllJKN+oliN9zw4nxlQK2pACJm5pWPKrKKQLj9IPbYkRoHJf/ETcAWrHQ85q2ecd669/eG97r8N1jAm9791CVp1urfvVVdUPGzjqJzmTuDqqtzTtrQcpaDy1ur6A2oHOTEBeT5n33gMYuP93BR6GcnVjiNj6v0JbGcbFH/TUjs/50GPoedyRVpSelnZmjEfIKO56wc8R8dYrnjbzzqNUnHmsVdD+EPNzE3a3W+0alx4ggVeXD+My7hmpob2RER9s+3aCtb9RmbklduRhYI+I="
    - secure: "podLXbNwvixLf++PytsN9bjNcLO2WaV4c9r0/6HeG56tf4eJBEGewMDqaUwZnbni3/Gnu4NwUhwKotInjJrebLX1XCpXbl3arZoXiB9E/qGcB6f+X8bM9K2jjwipd7sGuUJ97G8aNpF+eB144d2feIxSTWM5W+lZPbPMuVvGnONtywdMsqTsJuk0EFhVgncqYusND4rV59AYruiXm8K0DdDo8J99nTbRb2TF/t34hPDd5XlB/rnbNmEtDhbr0vyrZZh8+5N/SWii4QL23B7snmDr8JGnpgevdu0VfR5L/CtYNcz/KKeFiaPy6Ui4kvl2ivWCvfuWpkwSrl8O0GA3oYJ/y41F7SGXsKoAEtPU4Fesw8ro7pGZis04AAg2sCkgdsk3/BP3LVgFTGcP9rS+FQix0aRZGSCTJh/UwO/FRD/dDAgmihyx9Tzr3jYWmLvWEwd89L7BKB3WyVJpawgYy8nyVLaZXSKC147jhoI4Ml+0QWayGkAOL/xSZB+8rRYQ/NOejf2YakglRR2wv4LvjEIx9yoKbKYJnJKvR9ae0z13yRe1ozZCsjCXZlpmpKP/fZPQD70Kkv78fySOKZBRluvxciedmckU4BodCSm8qz/Ki9DT6UCmd37DTAE6TKYeb4niF+3SGrGO2TE/dBK9Xxvj7dbgtNYXmKvD2ZDLbow="
jobs:
 include:
    - stage: Test
      script:
        - npm run react-test
    - stage: Deploy Windows & Mac
      if: tag IS present
      os: osx
      osx_image: xcode10.1
      script:
        - npm run electron-publish -- --mac --win
      before_cache:
        - rm -rf $HOME/.cache/electron-builder/wine
    - stage: Deploy linux
      if: tag IS present
      os: linux
      dist: trusty
      script:
        - npm run electron-publish
    - stage: Deploy website
      script:
        - npm run react-build-web
      deploy:
        provider: s3
        access_key_id: $AWS_ACCESS_KEY_ID
        secret_access_key: $AWS_SECRET_ACCESS_KEY
        bucket: oncothreads.gehlenborglab.org
        local_dir: build
        skip_cleanup: true
        on:
          branch: master