language: node_js
install:
- nvm ls-remote # TODO: remove; just for debugging
# Install the node version specified in package.json:
# https://github.com/travis-ci/travis-ci/issues/4653#issuecomment-276949979
- nvm install "$(jq -r '.engines.node' package.json)"
script:
- npm install --dev
- ./tests.sh
- npm run build
deploy:
 provider: s3
 access_key_id: $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_ACCESS_KEY
 bucket: onco-app
 local_dir: build
 skip_cleanup: true
 on:
  branch: master
env:
  global:
  - secure: sgXSlUFRdXlSWLP3+7GGxTkHhgoNh3gY94J5VFTBbKEQmIjpfnV+5Wmb3bRP+btKaX9CTlvZPSNBqgAaIQZXj7eIRz6pylCuJeO+5x1SYvTPWIPfsZ9QKgGbSHrc7OKFU0fFRSwF1O+rLN2FRQxHn95hF/B5LEms1hJxiq61+rDiwT+wAokZDWphtS2fOHSMdndxXt8OD5mmgyQzlvj9MeG7MWzMBJLGBvjJdChwcuWbpDz/P3KxvkGgb9Qx2MKHq9ooTpXo8JtESOg6U2DmbHjZwyygy26YcxCWgMHdD1BgU/GlhXmGGsEd6xeuqlPvn86BCd3FFzWTx66v/UWzWywHzOKvSIq+eKKBkfO3v+kKjmv1xHJZWiQnw/G5t3YEJKB7LnIAifu374ne4WvMdirBWglaw1wj1tAC4PolstAluwzJ3uR5qQIoVmFO6Jx3jMoFzF7G1kxvVpFWfVxi35LMOu021ELRF5l6pbLFO8V7+kXdd0xouoU/vTy9RVSJhGczZRbVOwwk17BFsAW39UbpUzDrgJOWA7+VIlVyCUPChDymKks8X9eH1Ojk1aTIFuK3BCCcUtSXIG+uUAdgEQseJrayS1gzO1zP7CF/zZHH3GzVKmK4B4W3ftanMK1inXrWv/LVhRDQ+J+FrOw0QUZqgtYyAgwdlO9BWs4v1+Y=
  - secure: T66vBNQZfOmNfcCqY+9REOrL7+8n/OQcVq4RadGDNI3LDwynSWZ3026xH2PWoygLQcxKqveCEuzgwCCx9fOySN6eqW2bQW6scu9FaQsrOdirXFBgNOJvwzE5BRfZwG3jEIUUJ0E1kXz1vMApl6oWY0QwW09kkczCQKdX0wpcKbsZlL17SIHO8Gp4zpxafrKLcJ7K8eXwoWgM1BpaBAJ4ASGF8pn1/z7ZC1JFSTO1a9R2JZkQEAoUUcKkP5sycP1eZM25MPzC7vsZn3J3qUcm9UeFg539SyIhBa+ufBXehYiOcRfQhV5tEWWqN+91ywTNlYUoyEiO4KpXue46ATLl+sG+m+iPp3aQOz8pFV6bT3GA392xUpz6hMIntLZnGp0otmEIYeIfx//+HjzuTs++ZLvjlLQCLhU+zwmRzP4LqmmFWBr01pctVRra7fb2nUm5/Nwcw84P9GW5XPmW5qtreQpknoY0n4Cq2srqaNvAU7GZqdj7U6GFN9TdKZi3C94imXTb9+eoSJMnMJq9eLz85As/rhb5PZ+beohNu+YEQCrbgOU1OqIV0KHKyZtY4UNQaDk2jCprBtxxHFWadY06ek5r5Y6XUMXbhMm62rszy/oP/2bof2Lf+asRglzDBe0LUgROCYSQNnDnX9dQWnQXEH2LhbiPXfZKyUuNzBqSI/o=
